# Generated by Django 6.1.1 on 2026-09-16 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_api_key', models.CharField(blank=True, help_text="Required for AI recommendations. Get an OpenAI account; google 'openai api key'", max_length=255, null=True)),
                ('base_url', models.CharField(blank=True, help_text='ex: https://exceptbot.com', max_length=255, null=True)),
                ('project_name', models.CharField(blank=True, help_text="The directory name of your project. Ex: 'exceptbot'", max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'App Setting',
                'verbose_name_plural': 'App Settings',
            },
        ),
        migrations.CreateModel(
            name='ExceptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_type', models.CharField(db_index=True, max_length=255)),
                ('full_error_message', models.TextField(blank=True)),
                ('file_name', models.CharField(db_index=True, max_length=500)),
                ('file_content', models.TextField(blank=True)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('error_line_content', models.TextField(blank=True)),
                ('url_path', models.TextField(db_index=True)),
                ('http_method', models.CharField(db_index=True, default='GET', max_length=10)),
                ('status_code', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('source', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('unknown', 'Unknown')], db_index=True, default='backend', max_length=20)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('ai_suggestion', models.TextField(blank=True, null=True)),
                ('count', models.PositiveIntegerField(default=1)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_exceptions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caused_exceptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exception Log',
                'verbose_name_plural': 'Exception Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['is_resolved', '-timestamp'], name='exceptbot_e_is_reso_f0a0d5_idx'), models.Index(fields=['exception_type', 'file_name', 'is_resolved'], name='exceptbot_e_excepti_0cf5b5_idx'), models.Index(fields=['source', 'is_resolved'], name='exceptbot_e_source_e78949_idx')],
            },
        ),
    ]
